# =============================================================================
# Archivo    : pubspec.yaml
# Proyecto   : Control de visitas
# Descripción: Declaración de dependencias y metadatos del proyecto Flutter.
#              Versión mínima de Flutter aprobada para el proyecto.
# Autor      : Yadhira Andanely Benitez Millan
# Versión    : 1.0.0
# Fecha      : 2026-04-25
# Referencia : MPF-OMEGA-04 1.3, 1.4
# =============================================================================

name: control_visitas
description: Sistema institucional de gestión de accesos y visitas con control QR
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Gestión de estado — MVVM con ChangeNotifier (MPF-OMEGA-04 §6.1)
  provider: ^6.1.2

  # Cliente HTTP con interceptores (MPF-OMEGA-04 §6.5)
  dio: ^5.4.3+1

  # Almacenamiento seguro del token JWT (MPF-OMEGA-04 §6.7)
  flutter_secure_storage: ^9.0.0

  # Tipografía institucional: Montserrat + Inter (MPF-OMEGA-04 §7.2)
  google_fonts: ^6.2.1

  # Logs del sistema (MPF-OMEGA-04 §6.6)
  logger: ^2.3.0

  # Formateo de fechas en español
  intl: ^0.19.0

  # Localización oficial
  flutter_localizations:
    sdk: flutter

flutter:
  uses-material-design: true

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
